level:
  path: data/levels

theme:
  default: paper
  path: config/themes
  styles:
    base: config/themes/base.css
    creator: config/themes/creator.css

colors:
  path: config/colors

background:
  path: config/background
  image: "default.png"
  opacity: 0.2
  blur: 0px
